### PR TITLE
Various UI bug fixes

### LINKED ISSUE #27: Closing Toast
Button for closing the Toast needs to be smaller/clicking away to close would also be nice if possible

### PR DESCRIPTION
**Pull request by jeffreydivi**
# What changed?
- Various UI fixes for mobile
- Patch a bug where a first load may be buggy

# Testing
Tested using responsive design editor.

# Others
Closes #27, #28.

### CODE REVIEW

File: src/components/layout/Header.tsx [hunk 1]
```diff
@@ -24,7 +24,7 @@ function Header() {
   };
 
   let pfp = (
-    <Link to="/account/signin">
+    <Link to="/settings/profile/">
```
Comment (nategaulke) [inline src/components/layout/Header.tsx:27]: My opinion is that it should take you to the sign in page when not signed in, but I'm okay with this change too

**Review by nategaulke — APPROVED** [review]
Looks good, thanks for mobile optimizations Jeffrey
